[book]
authors = ["Molock Team"]
language = "en"
src = "src"
title = "Molock User Guide"

[output.html]
git-repository-url = "https://github.com/fike/molock"
edit-url-template = "https://github.com/fike/molock/edit/main/docs/book/{path}"
